controllers:
    resource: '../src/Controller/'
    type: annotation

contact_index:
    path: /contact/
    controller: App\Controller\ContactController::index

contact_create:
    path: /contact/create/
    controller: App\Controller\ContactController::create

contact_edit:
    path: /contact/{lastName}/edit/
    controller: App\Controller\ContactController::edit

contact_delete:
    path: /contact/{lastName}/
    controller: App\Controller\ContactController::delete