controllers:
    resource: '../src/Controller/'
    type: annotation

contact_index:
    path: /
    controller: App\Controller\ContactController::index

contact_create:
    path: /contact/create/
    controller: App\Controller\ContactController::create

contact_edit:
    path: /contact/edit/{firstName}
    controller: App\Controller\ContactController::edit

contact_delete:
    path: /contact/delete/{firstName}/
    controller: App\Controller\ContactController::delete